### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by oix29** [rkarami/ulauncher-password-generator#1]
Hello, 
While installing the extension on Ubuntu 21.04, I got this error : 

Message: 'com.github.rkarami.ulauncher-password-generator'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.rkarami.ulauncher-password-generator'

```

**Comment by itsOmidKarami** [comment]
@oix29 can you share some more info with me, please?
Like the OS version, Ulauncher version, the extension's configuration (make sure that you don't share personal data though!)
